const express = require('express')
const router = express.Router()
const protect = require('../middleware/authMiddleware')
const {addAdmin,authAdmin,getAdminProfile,updateAdminProfile} = require('../controllers/adminController')
const {updateMenuItem,deleteMenuItem}  = require('../controllers/restaurantController')
router.post('/register',addAdmin)
router.post('/login',authAdmin)
router.route('/profile').get(protect,getAdminProfile).put(protect,updateAdminProfile)
router.route('/updateMenuItem').put(protect,updateMenuItem)
router.route('/deleteMenuItem/:id/').delete(protect,deleteMenuItem)
module.exports = router
