const express = require('express')
const router = express.Router()
const protect = require('../middleware/authMiddleware')
const {addAdmin,authAdmin,getAdminProfile,updateAdminProfile} = require('../controllers/adminController')
const {updateMenuItem,deleteMenuItem}  = require('../controllers/restaurantController')
router.post('/register',addAdmin)
router.post('/login',authAdmin)
router.route('/profile').get(getAdminProfile).put(updateAdminProfile)
router.route('/updateMenuItem').put(protect,updateMenuItem)
router.route('/deleteMenuItem/:rest_id/:item_id').delete(protect,deleteMenuItem)
module.exports = router
