export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST'
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS'
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL'

export const ADMIN_DETAILS_REQUEST = 'ADMIN_DETAILS_REQUEST'
export const ADMIN_DETAILS_SUCCESS = 'ADMIN_DETAILS_SUCCESS'
export const ADMIN_DETAILS_FAIL = 'ADMIN_DETAILS_FAIL'

export const ADMIN_PROFILE_UPDATE_REQUEST = 'ADMIN_PROFILE_UPDATE_REQUEST'
export const ADMIN_PROFILE_UPDATE_SUCCESS = 'ADMIN_PROFILE_UPDATE_SUCCESS'
export const ADMIN_PROFILE_UPDATE_FAIL = 'ADMIN_PROFILE_UPDATE_FAIL'
export const ADMIN_PROFILE_RESET = 'ADMIN_PROFILE_RESET'

export const ADMIN_GET_ALL_ORDER_DETAILS_REQUEST = 'ADMIN_GET_ALL_ORDER_DETAILS_REQUEST'
export const ADMIN_GET_ALL_ORDER_DETAILS_SUCCESS = 'ADMIN_GET_ALL_ORDER_DETAILS_SUCCESS'
export const ADMIN_GET_ALL_ORDER_DETAILS_FAIL = 'ADMIN_GET_ALL_ORDER_DETAILS_FAIL'

export const ADMIN_CHANGE_ORDER_STATUS_REQUEST = 'ADMIN_CHANGE_ORDER_STATUS_REQUEST'
export const ADMIN_CHANGE_ORDER_STATUS_SUCCESS = 'ADMIN_CHANGE_ORDER_STATUS_SUCCESS'
export const ADMIN_CHANGE_ORDER_STATUS_FAIL = 'ADMIN_CHANGE_ORDER_STATUS_FAIL'