export const MENU_DETAILS_REQUEST = 'MENU_DETAILS_REQUEST'
export const MENU_DETAILS_SUCCESS = 'MENU_DETAILS_SUCCESS'
export const MENU_DETAILS_FAIL = 'MENU_DETAILS_FAIL'

export const MENU_ADD_REQUEST = 'MENU_ADD_REQUEST'
export const MENU_ADD_SUCCESS = 'MENU_ADD_SUCCESS'
export const MENU_ADD_FAIL = 'MENU_ADD_FAIL'
export const MENU_ADD_CLEAR = 'MENU_ADD_CLEAR'

export const MENU_GET_BY_ID_REQUEST = 'MENU_GET_BY_ID_REQUEST'
export const MENU_GET_BY_ID_SUCCESS = 'MENU_GET_BY_ID_SUCCESS'
export const MENU_GET_BY_ID_FAIL = 'MENU_GET_BY_ID_FAIL'