export const MENU_DETAILS_REQUEST = 'MENU_DETAILS_REQUEST'
export const MENU_DETAILS_SUCCESS = 'MENU_DETAILS_SUCCESS'
export const MENU_DETAILS_FAIL = 'MENU_DETAILS_FAIL'

export const MENU_ADD_REQUEST = 'MENU_ADD_REQUEST'
export const MENU_ADD_SUCCESS = 'MENU_ADD_SUCCESS'
export const MENU_ADD_FAIL = 'MENU_ADD_FAIL'