export const REST_LOGIN_REQUEST = 'REST_LOGIN_REQUEST'
export const REST_LOGIN_SUCCESS = 'REST_LOGIN_SUCCESS'
export const REST_LOGIN_FAIL = 'REST_LOGIN_FAIL'
export const REST_LOGOUT = 'REST_LOGOUT'

export const REST_REGISTER_REQUEST = 'REST_REGISTER_REQUEST'
export const REST_REGISTER_SUCCESS = 'REST_REGISTER_SUCCESS'
export const REST_REGISTER_FAIL = 'REST_REGISTER_FAIL'

export const REST_DETAILS_REQUEST = 'REST_DETAILS_REQUEST'
export const REST_DETAILS_SUCCESS = 'REST_DETAILS_SUCCESS'
export const REST_DETAILS_FAIL = 'REST_DETAILS_FAIL'

export const REST_PROFILE_UPDATE_REQUEST = 'REST_PROFILE_UPDATE_REQUEST'
export const REST_PROFILE_UPDATE_SUCCESS = 'REST_PROFILE_UPDATE_SUCCESS'
export const REST_PROFILE_UPDATE_FAIL = 'REST_PROFILE_UPDATE_FAIL'
export const REST_PROFILE_RESET = 'REST_PROFILE_RESET'

export const REST_ALL_DETAILS_REQUEST = 'REST_ALL_DETAILS_REQUEST'
export const REST_ALL_DETAILS_SUCCESS = 'REST_ALL_DETAILS_SUCCESS'
export const REST_ALL_DETAILS_FAIL = 'REST_ALL_DETAILS_FAIL'

