
const generateToken = require('../../utils/generateToken')
const db = require('../../dbCon')
const bcrypt = require('bcryptjs')
const User = require('../../Models/userModel')
const kafka = require('../../kafka/client')


const handle_request = async(msg, callback)=>{
    const { email, password } = msg
    const user = await User.findOne({ email: email })
    try {
        if (user && (await user.matchPassword(password))) {
            const result = {
                _id: user._id,
                firstName: user.firstName,
                lastName: user.lastName,
                email: user.email,
                token: generateToken(user._id), // token is generated by using a custom function and jsonwebtoken library. The custom function is available is utils/generatetokens.js
            }
            callback(null,result)
        }
        else {
           const err = {
                "error":"Invalid username/Password'"
            }
            callback( err,null);
           
        }
        
    } catch (error) {
        const err = {
            "error":"Internal Server Error"
        }
        callback( err,null);
        
    }
   
   
    
};

exports.handle_request = handle_request;