
const generateToken = require('../../../utils/generateToken')
const db = require('../../../dbCon')
const bcrypt = require('bcryptjs')
const Admin = require('../../../Models/adminModel')
const kafka = require('../../../kafka/client')


const handle_request = async(msg, callback)=>{
    const { email, password } = msg
    const admin = await Admin.findOne({ email: email })
    try {
        if (admin && (await admin.matchPassword(password))) {
            const result = {
                _id: admin._id,
                firstName: admin.firstName,
                lastName: admin.lastName,
                email: admin.email,
                token: generateToken(admin._id), // token is generated by using a custom function and jsonwebtoken library. The custom function is available is utils/generatetokens.js
            }
            callback(null,result)
        }
        else {
           const err = {
                "error":"Invalid username/Password'"
            }
            callback( err,null);
           
        }
        
    } catch (error) {
        console.log(error)
        const err = {
            "error":"Internal Server Error"
        }
        callback( err,null);
        
    }
   
   
    
};

exports.handle_request = handle_request;